 const DUMMY_EVENTS = [
  {
    id: 'e1',
    title: 'Web Development Conference 2025',
    description: 'Join us for the biggest web development conference of the year featuring the latest in React, Node.js, and modern web technologies.',
    date: '2025-07-15',
    time: '09:00',
    location: 'Tech Convention Center, San Francisco',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=500',
    category: 'Technology',
    price: 299,
    organizer: 'TechEvents Inc.',
    attendees: 1250,
    tags: ['React', 'JavaScript', 'Web Development', 'Networking']
  },
  {
    id: 'e2',
    title: 'Digital Marketing Summit',
    description: 'Learn the latest digital marketing strategies from industry experts. Topics include SEO, social media marketing, content strategy, and analytics.',
    date: '2025-08-22',
    time: '10:00',
    location: 'Business Hub, New York',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500',
    category: 'Marketing',
    price: 199,
    organizer: 'Marketing Pros',
    attendees: 800,
    tags: ['SEO', 'Social Media', 'Content Marketing', 'Analytics']
  },
  {
    id: 'e3',
    title: 'Music Festival - Summer Vibes',
    description: 'A 3-day outdoor music festival featuring indie bands, electronic music, and local artists. Food trucks and camping available.',
    date: '2025-06-28',
    time: '14:00',
    location: 'Greenfield Park, Austin',
    image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=500',
    category: 'Entertainment',
    price: 149,
    organizer: 'Festival Productions',
    attendees: 5000,
    tags: ['Music', 'Festival', 'Outdoor', 'Camping']
  },
  {
    id: 'e4',
    title: 'Startup Pitch Competition',
    description: 'Watch innovative startups pitch their ideas to a panel of investors. Network with entrepreneurs and venture capitalists.',
    date: '2025-09-10',
    time: '18:00',
    location: 'Innovation Center, Boston',
    image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=500',
    category: 'Business',
    price: 0,
    organizer: 'Startup Boston',
    attendees: 300,
    tags: ['Startup', 'Pitch', 'Investment', 'Networking']
  },
  {
    id: 'e5',
    title: 'Art & Design Workshop',
    description: 'Hands-on workshop covering digital art, UI/UX design principles, and creative process. All skill levels welcome.',
    date: '2025-07-05',
    time: '13:00',
    location: 'Creative Studio, Los Angeles',
    image: 'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=500',
    category: 'Education',
    price: 75,
    organizer: 'Design Academy',
    attendees: 50,
    tags: ['Design', 'Workshop', 'UI/UX', 'Digital Art']
  },
  {
    id: 'e6',
    title: 'Food & Wine Tasting',
    description: 'Exclusive tasting event featuring local wines paired with gourmet dishes prepared by renowned chefs.',
    date: '2025-08-14',
    time: '19:00',
    location: 'Riverside Restaurant, Portland',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500',
    category: 'Food & Drink',
    price: 125,
    organizer: 'Culinary Events',
    attendees: 120,
    tags: ['Wine', 'Food', 'Tasting', 'Gourmet']
  },
  {
    id: 'e7',
    title: 'Fitness Bootcamp Challenge',
    description: 'Intensive 4-hour fitness challenge with professional trainers. Test your limits and meet fellow fitness enthusiasts.',
    date: '2025-06-20',
    time: '07:00',
    location: 'Central Park, New York',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500',
    category: 'Health & Fitness',
    price: 45,
    organizer: 'FitLife Events',
    attendees: 200,
    tags: ['Fitness', 'Bootcamp', 'Challenge', 'Health']
  },
  {
    id: 'e8',
    title: 'Photography Exhibition Opening',
    description: 'Opening night for "Urban Landscapes" photography exhibition featuring works from 25 contemporary photographers.',
    date: '2025-07-30',
    time: '18:30',
    location: 'Modern Art Gallery, Chicago',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500',
    category: 'Arts & Culture',
    price: 25,
    organizer: 'Chicago Art Society',
    attendees: 150,
    tags: ['Photography', 'Exhibition', 'Art', 'Urban']
  }
];

export default DUMMY_EVENTS ;